# This is a basic workflow to help you get started with Actions

name: gh-pages

on:
  push:
    branches: ["*"]
    paths-ignore:
      - README.md
      - CONTRIBUTING.md
      - LICENSE.md
      - .gitignore
  pull_request:
    branches: ["*"]
    paths-ignore:
      - README.md
      - CONTRIBUTING.md
      - LICENSE.md
      - .gitignore
  release:
    types:
      - created
      - edited

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8" # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: "x64" # optional x64 or x86. Defaults to x64 if not specified

      - name: Install deps
        run: |-
          python -m pip install -r requirements-dev.txt

      - name: Build branch
        run: |-
          if [[ "$GITHUB_REF" = /refs/tags/* ]]; then
            TAG=$(echo "$GITHUB_REF" | sed "s/\/refs\/tags\///")
            SUBPATH="v$TAG/" # note the trailing slash
            echo "Building for TAG: $SUBPATH"
          else
            SUBPATH=$(echo "$GITHUB_HEAD_REF") # "${GITHUB_HEAD_REF}/" # note the trailing slash
            echo "Building for PR: $SUBPATH"
          fi
          echo "Publishing $SUBPATH"
          sphinx-build -b html docs/it/  html/$SUBPATH/it
          sphinx-build -b html docs/en/  html/$SUBPATH/en

      # Runs a single command using the runners shell
      - name: Create GH page index
        run: |-
          touch html/.nojekyll
          echo '
          <html>
          <head>
            <title>EUDI Wallet docs</title>
            <meta name="viewport" content="initial-scale=1.0">
          </head>
          <body>
          <h1>EUDI Wallet docs</h1>

          <ul>
            <li><a href="it/">Italian version</a></li>
            <li><a href="en/">English version</a></li>
          </ul>
          </body>
          </html>' > html/index.html

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: html
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
